services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_laravel
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    ports:
      - 8000:80   # ホストのポート8000をコンテナの80ポートにマッピング
