services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_laravel
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=hogemax
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - 8000:80
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hogemax
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
